CREATE TABLE IF NOT EXISTS "links" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "slug" VARCHAR(255) NOT NULL UNIQUE,
  "redirect_to" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "visits" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "referrer" VARCHAR(255) NOT NULL,
  "user_agent" VARCHAR(255) NOT NULL,
  "ip" VARCHAR(255) NOT NULL,
  "link_id" INTEGER NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY("link_id") REFERENCES "links"("id") ON DELETE CASCADE
);